# Cloudflare Pages配置
name = "pet-health-assistant"
compatibility_date = "2024-09-23"
pages_build_output_dir = ".vercel/output/static"

# 启用 Node.js 兼容性 (Edge Functions需要)
compatibility_flags = ["nodejs_compat"]

# 注意：Cloudflare Pages的构建配置需要在Dashboard中设置
# 构建命令：npm run build:cloudflare
# 输出目录：.vercel/output/static

[env.production]
# 生产环境变量在Cloudflare Dashboard设置