# Cloudflare Pages配置
name = "pet-health-assistant"
compatibility_date = "2024-09-23"
pages_build_output_dir = ".vercel/output/static"

# 启用 Node.js 兼容性 (Edge Functions需要)
compatibility_flags = ["nodejs_compat"]

[build]
# Cloudflare Pages构建命令应该是: npm run build:cloudflare
command = "npm run build:cloudflare"

[env.production]
# 生产环境变量在Cloudflare Dashboard设置